default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('DATABASE_PORT') { 5432 } %>
  username: <%= ENV.fetch('DATABASE_USER') { 'postgres' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { '' } %>

development:
  <<: *default
  database: meister-hackers_development

test:
  <<: *default
  database: meister-hackers_test

production:
  <<: *default
  adapter: postgresql
  database: meister-hackers_production
  url: <%= ENV['DATABASE_URL'] %>