default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('DATABASE_PORT') { 5432 } %>
  username: <%= ENV.fetch('DATABASE_USER') { 'postgres' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { '' } %>

development:
  <<: *default
  database: github-open-products_development

test:
  <<: *default
  database: github-open-products_test

production:
  <<: *default
  database: github-open-products_production
  username: github-open-products
  password: <%= ENV['GITHUB-OPEN-PRODUCTS_DATABASE_PASSWORD'] %>
